apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-config-decryptor-webhook.fullname" . }}
  labels: {{ include "spring-config-decryptor-webhook.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
  selector:
    {{- include "spring-config-decryptor-webhook.selectorLabels" . | nindent 4 }}
